# Generated by Django 5.1.3 on 2025-01-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('Big Event', 'Big Event'), ('Small Event', 'Small Event')], max_length=50)),
                ('number_of_people', models.CharField(max_length=50)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('event_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
