# Generated by Django 5.1.3 on 2025-01-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='specifications',
            field=models.TextField(default='No specifications provided'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Graduation', 'Graduation'), ('Private', 'Private '), ('Anniversary', 'Anniversary'), ('Unspecified', 'Unspecified')], max_length=50),
        ),
    ]
