# Generated by Django 5.1.3 on 2025-01-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_specifications_alter_booking_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_people',
            new_name='num_people',
        ),
    ]
