# Generated by Django 5.1.3 on 2025-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_booking_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
