# Generated by Django 5.1.3 on 2025-01-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_order_num_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderableitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orderable_items/'),
        ),
    ]
