# Generated by Django 5.1.3 on 2025-02-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_orderableitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='specifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='specifications',
            field=models.TextField(),
        ),
    ]
