# Generated by Django 5.1.3 on 2025-02-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
